### ISSUE TITLE
Design layout of this app

### ISSUE THREAD

**Issue by atrninkov1** [Draccarr/Hunted-Companion-App-Mobile#1]
**As a developer on this project
I want to have a clear vision of what it is that I am developing and know that it is what the client wants
so that I can focus on the development of the app**

Requirements:
- A mockup of what the app should look like needs to be sketched out and approved by the users

**Comment by JamesDesmarais** [comment]
I've completed the first draft of the Jay Command Screen

**Comment by JamesDesmarais** [comment]
![IMG_20200807_172408](https://user-images.githubusercontent.com/35913010/89697204-63f8b280-d8d8-11ea-9f1e-72be9dd7c323.jpg)

**Comment by JamesDesmarais** [comment]
![mobile-hunted-companion-app](https://user-images.githubusercontent.com/35913010/89702795-2c9efb80-d902-11ea-8ff1-e98d0abbfa67.png)

**Comment by JamesDesmarais** [comment]
A link to the Figma prototype:
https://www.figma.com/proto/bSxXb6OCenUCjA24iWqi53/Mobile-Hunted-Companion-App?node-id=3%3A2&scaling=scale-down

**Comment by JamesDesmarais** [comment]
- The Character profile page's notes lists will look similar to the desktop version.
- The Options menu will include configuration settings.
    > Font colour, Background colour, Foreground colour.
- A page to control Jay will be added, but that is a stretch goal for now. So after the MVP has been completed, that's when we can focus on that. Essentially we're replicating what we have on the desktop app first for our MVP.
